import CreateTrade from "./application/usecase/CreateTrade.ts";
import { Deposit } from "./application/usecase/Deposit.ts";
import ExecuteOrder from "./application/usecase/ExecuteOrder.ts";
import FillOrder from "./application/usecase/FillOrder.ts";
import GetOrder from "./application/usecase/GetOrder.ts";
import PlaceOrder from "./application/usecase/PlaceOrder.ts";
import Book from "./domain/Book.ts";
import OrderController from "./infra/controller/OrderController.ts";
import { PgPromiseAdapter } from "./infra/database/DatabaseConnection.ts";
import { AccountGatewayHttp } from "./infra/gateway/AccountGateway.ts";
import { MatchingEngineGatewayHttp } from "./infra/gateway/MatchingEngineGateway.ts";
import { PaymentGatewayHttp } from "./infra/gateway/PaymentGateway.ts";
import BookHandler from "./infra/handler/BookHandler.ts";
import Mediator from "./infra/handler/Mediator.ts";
import OrderHandler from "./infra/handler/OrderHandler.ts";
import { FetchAdapter } from "./infra/http/HttpClient.ts";
import { ExpressAdapter } from "./infra/http/HttpServer.ts";
import ORM from "./infra/orm/ORM.ts";
import { RabbitMQAdapter } from "./infra/queue/Queue.ts";
import { OrderRepositoryDatabase } from "./infra/repository/OrderRepository.ts";
import { TradeRepositoryDatabase } from "./infra/repository/TradeRepository.ts";
import { WalletRepositoryDatabase } from "./infra/repository/WalletRepository.ts";

async function main () {
    const databaseConnection = new PgPromiseAdapter();
    const httpServer = new ExpressAdapter();
    const queue = new RabbitMQAdapter();
    await queue.connect();
    await queue.setup("orderPlaced", "orderPlaced.insertOrder");
    await queue.setup("orderFilled", "orderFilled.fillOrder");
    await queue.setup("tradeCreated", "tradeCreated.createTrade");
    await queue.setup("depositCreated", "depositCreated.processPayment");
    // const httpServer = new HapiAdapter();
    // const httpClient = new AxiosAdapter();
    const httpClient = new FetchAdapter();
    const mediator = new Mediator();
    const orm = new ORM(databaseConnection);
    // const accountRepository = new AccountRepositoryDatabase(databaseConnection);
    const book = new Book("BTC-USD");
    const orderRepository = new OrderRepositoryDatabase(databaseConnection);
    const tradeRepository = new TradeRepositoryDatabase(databaseConnection);
    const walletRepository = new WalletRepositoryDatabase(databaseConnection);
    const paymentGateway = new PaymentGatewayHttp(httpClient);
    const accountGateway = new AccountGatewayHttp(httpClient);
    const matchingEngineGateway = new MatchingEngineGatewayHttp(httpClient);
    const deposit = new Deposit(accountGateway, walletRepository, paymentGateway);
    const executeOrder = new ExecuteOrder(orderRepository, tradeRepository);
    const placeOrder = new PlaceOrder(accountGateway, orderRepository, mediator);
    const getOrder = new GetOrder(orderRepository);
    const fillOrder = new FillOrder(orderRepository);
    const createTrade = new CreateTrade(tradeRepository);
    new OrderHandler(mediator, executeOrder, book, orderRepository, matchingEngineGateway, queue, fillOrder, createTrade);
    new BookHandler(book, fillOrder, createTrade);
    new OrderController(httpServer, placeOrder, getOrder, fillOrder, createTrade);
    httpServer.listen(3001);
}

main();
